### ISSUE TITLE
[Windows] AttributeError: 'FigureCanvasTkAgg' object has no attribute 'set_window_title'

### ISSUE THREAD

**Issue by infinity1729** [Udayraj123/OMRChecker#55]
## Environment
Windows OS, with matlplotlib version >=3.6.0

## Steps to reproduce

1) Open `OMRChecker\src\defaults\config.json`
2) Line 24: Set show image level to anything >=5 say `"show_image_level": 5,`
3) From the command line run: `python3 main.py -i samples/sample1`

## Details
```
(1) Opening image:      inputs\sample1\MobileCamera\sheet1.jpg  Resolution: (1240, 930)
Found page corners:      [[519, 541], [148, 537], [141, 220], [479, 218]]
Matching Marker:         Q1: max_t 0.451        Q2: max_t 0.582 Q3: max_t 0.692Q4: max_t 0.547  Optimal Scale: 0.46
Thresholding:            global_thr:  175.25    global_std_THR:  255
Traceback (most recent call last):
  File "C:\OMRChecker\main.py", line 79, in <module>
    entry_point(
  File "C:\OMRChecker\src\core.py", line 50, in entry_point
    return process_dir(root_dir, curr_dir, args)
  File "C:\OMRChecker\src\core.py", line 120, in process_dir
    process_dir(root_dir, d, args, template)
  File "C:\OMRChecker\src\core.py", line 120, in process_dir
    process_dir(root_dir, d, args, template)
  File "C:\OMRChecker\src\core.py", line 109, in process_dir
    process_files(omr_files, template, args_local, out)
  File "C:\OMRChecker\src\core.py", line 313, in process_files
    response_dict, final_marked, multi_marked, _ = MainOperations.read_response(
  File "C:\OMRChecker\src\utils\imgutils.py", line 993, in read_response
    raise e
  File "C:\OMRChecker\src\utils\imgutils.py", line 951, in read_response
    f.canvas.set_window_title(name)
AttributeError: 'FigureCanvasTkAgg' object has no attribute 'set_window_title'
```

This issue is potentially caused by latest release of matplotlib. (Refer: https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.6.0.html#:~:text=get_figure_manager%3B%20use-,frame.canvas.manager,-instead.)

**Comment by Udayraj123** [comment]
Do you wish to pick this up by yourself? I can assign it to you.

**Comment by infinity1729** [comment]
Yes, I am interested to work on this. Thanks for assigning it to me.

**Comment by Udayraj123** [comment]
Closing this issue as resolved.
