### ISSUE TITLE
[Bug][Windows] TypeError: unsupported operand type(s) for *: 'DotMap' and 'float'

### ISSUE THREAD

**Issue by infinity1729** [Udayraj123/OMRChecker#62]
## Description
Multiplication is being performed between DotMap and float data type, for image level 2,3.

## Steps to reproduce
1. Open OMRChecker\src\defaults\config.json
2. Line 24: Set show image level to either 2 or 3 say "show_image_level": 2,
3. From the command line run: python3 main.py -i samples/sample1

## Expected behaviour
window size gets increased by 1.6 times for image level 2,3.

## Error log
```Traceback (most recent call last):
  File "C:\OMRChecker\main.py", line 79, in <module>
    entry_point(
  File "C:\OMRChecker\src\core.py", line 50, in entry_point
    return process_dir(root_dir, curr_dir, args)
  File "C:\OMRChecker\src\core.py", line 120, in process_dir
    process_dir(root_dir, d, args, template)
  File "C:\OMRChecker\src\core.py", line 109, in process_dir
    process_files(omr_files, template, args_local, out)
  File "C:\OMRChecker\src\core.py", line 283, in process_files
    in_omr = pre_processor.apply_filter(in_omr, args)
  File "C:\OMRChecker\src\processors\CropOnMarkers.py", line 218, in apply_filter  
    h_stack, int(config.display_width * 1.6)),
TypeError: unsupported operand type(s) for *: 'DotMap' and 'float
```
## Environment
Windows OS
Python 3.10.7
OpenCV 4.6.0

**Comment by infinity1729** [comment]
I am interested to solve this issue myself. @Udayraj123 Please assign this issue to me.
